name: Build and Push

on:
  push:
    branches:
    - main
    - develop

env:
  IMAGE_NAME: ${{ secrets.DOCKER_REGISTRY }}/darty-fe
  HELM_REPO: https://x-access-token:${{ secrets.HELM_REPO_PAT }}@github.com/nahoczki/darty-fe-helm.git
  HELM_REPO_DIR: darty-fe-helm
  CHART_PATH: ./darty-fe-helm

jobs:
  build-and-update-helm:
    runs-on: self-hosted

    steps:
    - name: Checkout source code
      uses: actions/checkout@v3

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v2

    - name: Log in to private Docker registry
      uses: docker/login-action@v2
      with:
        registry: ${{ secrets.DOCKER_REGISTRY }}
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}

    - name: Build and push Docker image
      uses: docker/build-push-action@v4
      with:
        context: .
        file: ./Dockerfile
        push: true
        tags: ${{ env.IMAGE_NAME }}:${{ github.sha.substring(0, 7) }}

    - name: Set environment variables based on branch
      id: set_env
      run: |
        if [[ "${GITHUB_REF}" == "refs/heads/main" ]]; then
          echo "ENV=prod" >> $GITHUB_ENV
          echo "VALUES_FILE=values-prod.yaml" >> $GITHUB_ENV
          echo "HELM_BRANCH=prod" >> $GITHUB_ENV
        elif [[ "${GITHUB_REF}" == "refs/heads/develop" ]]; then
          echo "ENV=dev" >> $GITHUB_ENV
          echo "VALUES_FILE=values-dev.yaml" >> $GITHUB_ENV
          echo "HELM_BRANCH=dev" >> $GITHUB_ENV
        else
          echo "ENV=unknown" >> $GITHUB_ENV
          echo "VALUES_FILE=values.yaml" >> $GITHUB_ENV
          echo "HELM_BRANCH=main" >> $GITHUB_ENV
        fi

    - name: Clone private Helm chart repo
      run: |
        git clone ${{ env.HELM_REPO }} ${{ env.HELM_REPO_DIR }}

    - name: Checkout or create Helm branch
      working-directory: ${{ env.HELM_REPO_DIR }}
      run: |
        git fetch origin
        if git show-ref --verify --quiet refs/heads/${{ env.HELM_BRANCH }}; then
          git checkout ${{ env.HELM_BRANCH }}
        else
          git checkout -b ${{ env.HELM_BRANCH }}
        fi

    - name: Update image tag in Helm chart repo values file
      run: |
        sed -i "s/tag: .*/tag: ${{ github.sha }}/" ${{ env.HELM_REPO_DIR }}/${{ env.CHART_PATH }}/${{ env.VALUES_FILE }}

    - name: Commit and push changes to Helm branch
      working-directory: ${{ env.HELM_REPO_DIR }}
      run: |
        git config user.name "darty-autobot"
        git config user.email "darty@zoli.sh"
        git add .
        git diff --cached --quiet || git commit -m "Update image tag to ${{ github.sha }} for ${{ env.ENV }} environment [skip ci]"
        git push origin ${{ env.HELM_BRANCH }}
